### ISSUE TITLE
Unclear "PHP Fatal error:  Uncaught Exception: OSM API returned error code 0"

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/sc-statistics-service#18]
I have not yet researched this, I am planning to do this. But if someone knows what is going on here then - please let me know.

https://github.com/streetcomplete/sc-statistics-service/blob/master/classes/ChangesetModifiedElementsFetcher.class.php#L30

It could be related to not providing OSM user login

```
    const OSM_API_USER = null;
    const OSM_API_PASS = null;
```

which may result in rate limiting or blocking access (but at least initially is not)

```
mateusz@mateusz-virtualbox:~/Desktop/sc_statistics_service_development/sc-statistics-service$ php update_users.php 1722488
analyzing...
1722488
PHP Fatal error:  Uncaught Exception: OSM API returned error code 0 in /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/classes/ChangesetModifiedElementsFetcher.class.php:30
Stack trace:
#0 /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/classes/ChangesetAnalyzer.class.php(45): ChangesetModifiedElementsFetcher->fetch()
#1 /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/classes/ChangesetAnalyzer.class.php(23): ChangesetAnalyzer->getSolvedQuestsCountOfChangeset()
#2 /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/classes/ChangesetsWalker.class.php(115): ChangesetAnalyzer->analyze()
#3 /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/classes/ChangesetsWalker.class.php(75): ChangesetsWalker->analyzeChangesets()
#4 /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/update_users.php(30): ChangesetsWalker->analyzeUser()
#5 {main}
  thrown in /home/mateusz/Desktop/sc_statistics_service_development/sc-statistics-service/classes/ChangesetModifiedElementsFetcher.class.php on line 30
```

EDIT: trying https://stackoverflow.com/a/10228081/4130619

**Comment by matkoniecz** [comment]
> OSM API returned error code 0 curl reports Failed to connect to api.openstreetmap.org port 443: No route to host

maybe logging and retrying would be a good idea? No idea what is causing it, possibly my internet is not so great?

Or at least crash wit more clear message?
