### ISSUE TITLE
Uncaught Error: Class 'ChangesetModifiedElementsParser' not found

### ISSUE THREAD

**Issue by lukashass** [streetcomplete/sc-statistics-service#8]
When fetching `http://localhost:8080/get_statistics.php?user_id=<USER_ID>` I'm receiving the following error:

```
Fatal error: Uncaught Error: Class 'ChangesetModifiedElementsParser' not found in /workspace/classes/ChangesetElementIdsFetcher.class.php:19
Stack trace:
#0 /workspace/classes/ChangesetAnalyzer.class.php(17): ChangesetElementIdsFetcher->__construct(NULL, NULL)
#1 /workspace/classes/ChangesetsWalker.class.php(36): ChangesetAnalyzer->__construct(Object(mysqli), 'mariadb', NULL, NULL)
#2 /workspace/get_statistics.php(31): ChangesetsWalker->__construct(Object(mysqli), 'mariadb', NULL, NULL) #3 {main} thrown in /workspace/classes/ChangesetElementIdsFetcher.class.php on line 19
```

I then replaced `ChangesetModifiedElementsParser` with `ChangesetElementIdsParser`, but received the next error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to ChangesetElementIdsParser::parseElements() must be of the type array, object given, called in /workspace/classes/ChangesetElementIdsParser.class.php on line 16 and defined in /workspace/classes/ChangesetElementIdsParser.class.php:23
```

The environment I used is outlined in #7.

I suspect that the files in this repository are not up to date with what is actually deployed.

**Comment by westnordost** [comment]
Oh, yes. It looks like I forgot to commit a few files. I did that now, should work now.
